[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
solana_twitter = "EfpUgYt1dqvkdG2mneNUeDwW8PB9NBuVxFqMfK5vkgjG"

[programs.devnet]
solana_twitter = "EfpUgYt1dqvkdG2mneNUeDwW8PB9NBuVxFqMfK5vkgjG"

[programs.mainnet]
solana_twitter = "EfpUgYt1dqvkdG2mneNUeDwW8PB9NBuVxFqMfK5vkgjG"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/Users/shada/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
copy-idl = "mkdir -p app/src/idl && cp target/idl/solana_twitter.json app/src/idl/solana_twitter.json"

[test]
startup_wait = 500

[workspace]
types = "app/src/idl/"

